### ISSUE TITLE
Bug in Matrix example with Switch Class

### ISSUE THREAD

**Issue by mrmattson** [oosmos/oosmos#2]
Hello! First, thanks for your work on this project, I love the idea!

I found a bug in the Matrix example. When a button on the keypad is pressed, all switches in that button's column fire the Close_Event on the subscriber list, followed closely by the Open_Event on the subscriber list, same time. I found this is due to the switches all using the same column pin; the Matrix Class calls the swRunStateMachine() on [line 72 of matrix.c](https://www.oosmos.com/classes#id_Matrix_Class_'matrix') and each switch in the column also runs swRunStateMachine() on [line 66 of sw.c](https://www.oosmos.com/classes#id_Switch_Class_'sw').

To recreate this issue, wire a keypad per the diagram on the [matrix example webpage](https://www.oosmos.com/examples/matrix) and then compile and run the code on Arduino. In the serial console, any button held will show all buttons in that column as "Pressed" and then immediately "Released", with this repeating as fast as the controller cycles through the keypad matrix back to the held button.

To create the correct behavior, commend out [line 66 of sw.c](https://www.oosmos.com/classes#id_Switch_Class_'sw'), compile, and run on Arduino. Holding a button will only fire the "Pressed" event once and nothing else will happen until the button is released.

I noticed there is a swNewDetached() and swNew() in the sw.c/sw.h files. Currently, the exact same functionality happens regardless of which is called. Is one of these supposed to be a non-active object, aka [line 66 of sw.c](https://www.oosmos.com/classes#id_Switch_Class_'sw') commented out, to use the Switch Class in other classes? If so, which one is it: swNewDetached() or swNew()?

Thank you!

Side Note: a possible bug (or feature?) of the Matrix Class after correcting this bug is multiple buttons will be read if they are in different columns, regardless of row. However, the Matrix Class cannot read buttons pressed in the same column. This obvious from the algorithm once seen, but wanted to bring this up in case that's not the intent.

**Comment by oosmos** [comment]
Hello @mrmattson!  So sorry I didn't see your bug report until today.  I will research this and get back to you -- probably next weekend.  

Thanks.
Mark Glenn

**Comment by oosmos** [comment]
@mrmattson - I fixed the issue.  I have a few more process-related things to wrap up before officially releasing it, but here are the two functions that changed in `sw.c`:

```
extern sw * swNewDetached(pin * pPin)
{
  oosmos_Allocate(pSwitch, sw, swMaxSwitches, NULL);

  pSwitch->m_pPin  = pPin;
  pSwitch->m_State = Unknown_State;

  oosmos_SubscriberListInit(pSwitch->m_CloseEvent);
  oosmos_SubscriberListInit(pSwitch->m_OpenEvent);

  return pSwitch;
}

extern sw * swNew(pin * pPin)
{
  sw * pSwitch = swNewDetached(pPin);

  oosmos_ActiveObjectInit(pSwitch, m_ActiveObject, swRunStateMachine);

  return pSwitch;
}
```

After this change, you should be able to press and release any button in the keypad matrix independently.  Curiously, this is the way the code was originally. It was a regression introduced in Jan 2019.

Thank you very much for reporting this.

Mark

**Comment by oosmos** [comment]
V2.5.7 has been released with the fix for the bug you reported.  Thanks @mrmattson!

**Comment by mrmattson** [comment]
Glad I could help. I'm new to this framework and didn't feel I had enough of the concept internalized to write a patch and submit it. I'm excited to see the way it should be.

**Comment by oosmos** [comment]
Matthew, 

If you need any help with OOSMOS or state machines in general, I'm happy to help.

Regards,
Mark
